import { ServiceProvider } from "@/types";

export const providers: ServiceProvider[] = [
  {
    id: 1,
    email: "jonesadam@gmail.com",
    phoneNumber: "+447700900123",
    postcode: "NW1 4BT",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Housekeeping",
    createdAt: "2025-02-12",
    status: "Onboarded",
  },
  {
    id: 2,
    email: "info@homehelpers.co.uk",
    phoneNumber: "+447700900456",
    postcode: "E2 8AA",
    registrationStatus: "Inactive",
    vendorType: "Independent",
    serviceOffering: "Window Cleaning",
    createdAt: "2025-03-10",
    status: "Rejected",
  },
  {
    id: 3,
    email: "sarah.wilson@cleanpro.com",
    phoneNumber: "+447700900789",
    postcode: "SW3 2DY",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Car Valet",
    createdAt: "2025-01-15",
    status: "Onboarded",
  },
  {
    id: 4,
    email: "michael.brown@gmail.com",
    phoneNumber: "+447700901234",
    postcode: "M1 3NG",
    registrationStatus: "Active",
    vendorType: "Independent",
    serviceOffering: "Housekeeping",
    createdAt: "2025-03-18",
    status: "Onboarded",
  },
  {
    id: 5,
    email: "contact@sparkleservices.co.uk",
    phoneNumber: "+447700905678",
    postcode: "B2 4QA",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Window Cleaning",
    createdAt: "2025-02-28",
    status: "Onboarded",
  },
  {
    id: 6,
    email: "lisa.garcia@gmail.com",
    phoneNumber: "+447700909012",
    postcode: "L1 8JQ",
    registrationStatus: "Inactive",
    vendorType: "Independent",
    serviceOffering: "Car Valet",
    createdAt: "2025-03-05",
    status: "Rejected",
  },
  {
    id: 7,
    email: "info@pristineclean.com",
    phoneNumber: "+447700903456",
    postcode: "LS1 6DT",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Housekeeping",
    createdAt: "2025-01-22",
    status: "Onboarded",
  },
  {
    id: 8,
    email: "david.johnson@outlook.com",
    phoneNumber: "+447700907890",
    postcode: "G1 1RE",
    registrationStatus: "Active",
    vendorType: "Independent",
    serviceOffering: "Window Cleaning",
    createdAt: "2025-03-12",
    status: "Onboarded",
  },
  {
    id: 9,
    email: "admin@elitecare.co.uk",
    phoneNumber: "+447700901122",
    postcode: "CF10 3AT",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Car Valet",
    createdAt: "2025-02-08",
    status: "Onboarded",
  },
  {
    id: 10,
    email: "jennifer.lee@gmail.com",
    phoneNumber: "+447700904455",
    postcode: "EH1 2NG",
    registrationStatus: "Inactive",
    vendorType: "Independent",
    serviceOffering: "Housekeeping",
    createdAt: "2025-03-20",
    status: "Rejected",
  },
  {
    id: 11,
    email: "support@quickclean.com",
    phoneNumber: "+447700906677",
    postcode: "SO14 2AA",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Window Cleaning",
    createdAt: "2025-01-30",
    status: "Onboarded",
  },
  {
    id: 12,
    email: "robert.taylor@yahoo.com",
    phoneNumber: "+447700908899",
    postcode: "PL1 2AB",
    registrationStatus: "Active",
    vendorType: "Independent",
    serviceOffering: "Car Valet",
    createdAt: "2025-03-14",
    status: "Onboarded",
  },
  {
    id: 13,
    email: "hello@perfectservices.co.uk",
    phoneNumber: "+447700902244",
    postcode: "NE1 4ST",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Housekeeping",
    createdAt: "2025-02-18",
    status: "Onboarded",
  },
  {
    id: 14,
    email: "emma.davis@hotmail.com",
    phoneNumber: "+447700905566",
    postcode: "CV1 2GF",
    registrationStatus: "Inactive",
    vendorType: "Independent",
    serviceOffering: "Window Cleaning",
    createdAt: "2025-03-07",
    status: "Rejected",
  },
  {
    id: 15,
    email: "info@supremeclean.com",
    phoneNumber: "+447700907788",
    postcode: "OX1 1PT",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Car Valet",
    createdAt: "2025-01-25",
    status: "Onboarded",
  },
  {
    id: 16,
    email: "paul.martinez@gmail.com",
    phoneNumber: "+447700900011",
    postcode: "CB1 1PT",
    registrationStatus: "Active",
    vendorType: "Independent",
    serviceOffering: "Housekeeping",
    createdAt: "2025-03-16",
    status: "Onboarded",
  },
  {
    id: 17,
    email: "contact@goldstarclean.co.uk",
    phoneNumber: "+447700903344",
    postcode: "BA1 1LN",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Window Cleaning",
    createdAt: "2025-02-05",
    status: "Onboarded",
  },
  {
    id: 18,
    email: "amanda.white@outlook.com",
    phoneNumber: "+447700906655",
    postcode: "TN1 1YZ",
    registrationStatus: "Inactive",
    vendorType: "Independent",
    serviceOffering: "Car Valet",
    createdAt: "2025-03-09",
    status: "Rejected",
  },
  {
    id: 19,
    email: "team@royalclean.com",
    phoneNumber: "+447700908877",
    postcode: "PE1 1XF",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Housekeeping",
    createdAt: "2025-01-18",
    status: "Onboarded",
  },
  {
    id: 20,
    email: "kevin.thompson@gmail.com",
    phoneNumber: "+447700901199",
    postcode: "YO1 7LS",
    registrationStatus: "Active",
    vendorType: "Independent",
    serviceOffering: "Window Cleaning",
    createdAt: "2025-03-22",
    status: "Onboarded",
  },
  {
    id: 21,
    email: "info@diamondservices.co.uk",
    phoneNumber: "+447700904433",
    postcode: "CT1 1DX",
    registrationStatus: "Active",
    vendorType: "Company",
    serviceOffering: "Car Valet",
    createdAt: "2025-02-12",
    status: "Onboarded",
  },
  {
    id: 22,
    email: "rachel.anderson@hotmail.com",
    phoneNumber: "+447700907722",
    postcode: "TR1 1JN",
    registrationStatus: "Inactive",
    vendorType: "Independent",
    serviceOffering: "Housekeeping",
    createdAt: "2025-03-11",
    status: "Rejected",
  },
  // Add more rows...
];
